//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task_11_8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyInfo
    {
        public int ID { get; set; }
        public string FatherName { get; set; }
        public string FatherPhone { get; set; }
        public Nullable<int> StdID { get; set; }
    
        public virtual Students Students { get; set; }
    }
}
